name             'role-mongodb-mongos'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures role-mongodb-mongos'
long_description 'Installs/Configures role-mongodb-mongos'
version          '0.1.0'

depends 'mongodb', '0.16.1'
depends 'yum'
depends 'hostsfile'
